import 'package:cashify/features/transaction/data/models/movement_model.dart';
import 'package:cashify/features/transaction/domain/entities/movement_entity.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

class MovementRepository {
  final FirebaseFirestore _firestore;
  final FirebaseAuth _auth;

  MovementRepository(this._firestore, this._auth);

  String get _currentUid {
    final uid = _auth.currentUser?.uid;
    if (uid == null) throw Exception("Usuario no autenticado");
    
    return uid;
  }

  String _getMovementsPath(int year, int month) {
    final periodId = "${year}_$month";

    return "users/$_currentUid/billing_periods/$periodId/movements";
  }

  Future<void> save(MovementEntity m) async {
    final path = _getMovementsPath(m.billingPeriodYear, m.billingPeriodMonth);

    try {
      await _firestore
          .collection(path)
          .add(
            MovementModel(
              id: '',
              /* ID will be generated by Firestore */
              categoryId: m.categoryId,
              description: m.description,
              source: m.source,
              quantity: m.quantity,
              amount: m.amount,
              currentInstallment: m.currentInstallment,
              totalInstallments: m.totalInstallments,
              paymentMethodId: m.paymentMethodId,
              billingPeriodMonth: m.billingPeriodMonth,
              billingPeriodYear: m.billingPeriodYear,
              notes: m.notes,
              isCompleted: m.isCompleted,
            ).toFirestore(),
          );
    } catch (e) {
      debugPrint("Error saving movement: $e");
      rethrow;
    }
  }

  Future<void> update(MovementEntity m) async {
    final path = _getMovementsPath(m.billingPeriodYear, m.billingPeriodMonth);

    try {
      await _firestore
          .collection(path)
          .doc(m.id)
          .update(
            MovementModel(
              id: m.id,
              categoryId: m.categoryId,
              description: m.description,
              source: m.source,
              quantity: m.quantity,
              amount: m.amount,
              currentInstallment: m.currentInstallment,
              totalInstallments: m.totalInstallments,
              paymentMethodId: m.paymentMethodId,
              billingPeriodMonth: m.billingPeriodMonth,
              billingPeriodYear: m.billingPeriodYear,
              notes: m.notes,
              isCompleted: m.isCompleted,
            ).toFirestore(),
          );
    } catch (e) {
      debugPrint("Error updating movement: $e");
      rethrow;
    }
  }

  Future<void> delete(MovementEntity m) async {
    final path = _getMovementsPath(m.billingPeriodYear, m.billingPeriodMonth);

    try {
      await _firestore.collection(path).doc(m.id).delete();
    } catch (e) {
      debugPrint("Error deleting movement: $e");
      rethrow;
    }
  }

  Future<List<MovementEntity>> fetchByPeriod(int year, int month) async {
    final path = _getMovementsPath(year, month);

    try {
      final snapshot = await _firestore
          .collection(path)
          .orderBy('createdAt', descending: true)
          .get();

      return snapshot.docs.map((doc) {
        return MovementModel.fromFirestore(doc.data(), doc.id);
      }).toList();
    } catch (e) {
      debugPrint("Error fetching movements: $e");
      rethrow;
    }
  }
}
