import 'package:cashify/features/transaction/data/models/movement_model.dart';
import 'package:cashify/features/transaction/domain/entities/movement_entity.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

class MovementRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<void> save(MovementEntity m) async {
    final user = _auth.currentUser;

    if (user == null) throw Exception("Usuario no autenticado");

    final path = getMovementsPath(
      user.uid,
      m.billingPeriodYear,
      m.billingPeriodMonth,
    );

    try {
      await _firestore
          .collection(path)
          .add(
            MovementModel(
              id: '',
              /* ID will be generated by Firestore */
              categoryId: m.categoryId,
              description: m.description,
              source: m.source,
              quantity: m.quantity,
              amount: m.amount,
              currentInstallment: m.currentInstallment,
              totalInstallments: m.totalInstallments,
              paymentMethodId: m.paymentMethodId,
              billingPeriodMonth: m.billingPeriodMonth,
              billingPeriodYear: m.billingPeriodYear,
              notes: m.notes,
              isCompleted: m.isCompleted,
            ).toFirestore(),
          );
    } catch (e) {
      debugPrint("Error saving movement: $e");
      rethrow;
    }
  }

  Future<void> update(MovementEntity m) async {
    final user = _auth.currentUser;

    if (user == null) throw Exception("Usuario no autenticado");

    final path = getMovementsPath(
      user.uid,
      m.billingPeriodYear,
      m.billingPeriodMonth,
    );

    try {
      await _firestore
          .collection(path)
          .doc(m.id)
          .update(
            MovementModel(
              id: m.id,
              categoryId: m.categoryId,
              description: m.description,
              source: m.source,
              quantity: m.quantity,
              amount: m.amount,
              currentInstallment: m.currentInstallment,
              totalInstallments: m.totalInstallments,
              paymentMethodId: m.paymentMethodId,
              billingPeriodMonth: m.billingPeriodMonth,
              billingPeriodYear: m.billingPeriodYear,
              notes: m.notes,
              isCompleted: m.isCompleted,
            ).toFirestore(),
          );
    } catch (e) {
      debugPrint("Error updating movement: $e");
      rethrow;
    }
  }

  Future<void> delete(MovementEntity m) async {
    final user = _auth.currentUser;

    if (user == null) throw Exception("Usuario no autenticado");

    final path = getMovementsPath(
      user.uid,
      m.billingPeriodYear,
      m.billingPeriodMonth,
    );

    try {
      await _firestore.collection(path).doc(m.id).delete();
    } catch (e) {
      debugPrint("Error deleting movement: $e");
      rethrow;
    }
  }

  Future<List<MovementEntity>> fetchByPeriod(int year, int month) async {
    final user = _auth.currentUser;

    if (user == null) throw Exception("Usuario no autenticado");

    final path = getMovementsPath(user.uid, year, month);

    try {
      final snapshot = await _firestore
          .collection(path)
          .orderBy('createdAt', descending: true)
          .get();

      return snapshot.docs.map((doc) {
        return MovementModel.fromFirestore(doc.data(), doc.id);
      }).toList();
    } catch (e) {
      debugPrint("Error fetching movements: $e");
      rethrow;
    }
  }

  String getMovementsPath(String uid, int year, int month) {
    final periodId = "${year}_$month";

    return "users/$uid/billing_periods/$periodId/movements";
  }
}
